ethereum_rpc   = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc    = "https://relay.hoodi.drosera.io"
eth_chain_id   = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.basefee_surge]
path = "out/BasefeeSurgeTrap.sol/BasefeeSurgeTrap.json"
response_contract = "0x7eDBCA1450f90F1927cb5721302a209D1e109fc9"
response_function = "respondToBasefee(uint256,uint256)"
block_sample_size = 2
cooldown_period_blocks = 20
private_trap = true
whitelist = ["0x8b75540D19629C135D2822EEfb124838AC0b0f68"]
